version: '3'

services:
  sukify_db:
    image: mysql:latest
    restart: unless-stopped
    container_name: sukify_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - sukify

  sukify_frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
    container_name: sukify_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - sukify
    #labels:
      #- "traefik.http.routers.sukify.rule=Host(`sukify.yourdomainename.example`)"
      #- "traefik.http.routers.sukify.tls=true"
      #- "traefik.http.routers.sukify.entrypoints=https,http"
      #- "traefik.http.routers.sukify.tls.certresolver=example"
      #- "traefik.http.services.sukify.loadbalancer.server.port=80"
      #- "traefik.enable=true"

  sukify_backend:
    build:
      dockerfile: Dockerfile
      context: ./server
      args:
        USER: "user"
        PASSWORD: "password"
        YOUTUBE_API_KEY: "YOUR API KEY"
    container_name: sukify_backend
    restart: unless-stopped
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/sukify
    links:
      - sukify_db
    networks:
      - sukify

networks:
  sukify:
    driver: bridge
